### PR TITLE
fixed some bugs and added Django admin integration

### PR DESCRIPTION
**Pull request by seroy**

### CODE REVIEW

**Comment by Photonios** [comment]
I am currently in holiday so I don't have the time to go through this completely. But, I would like to thank you for your contribution. It is much appreciated.

After new years, I'll be back at work and we can see how we can get this merged. Again, thanks for your contribution :)

**Comment by si14** [comment]
Hi @Photonios, will you have a chance to look at the changes? I understand that those are pretty heavy, but it would be awesome if it is still possible to get them into upstream. I would be happy to help if you find something that still needs work in this PR.

**Comment by Photonios** [comment]
My apologies for not replying to this.

My main concerns with upstreaming this "as is" would be that it includes jQuery. I have no strong objections against jQuery. However, this is a library that people would include into their projects, by pulling it in, they'd also be pulling in a heavy dependency on jQuery. This could cause all sorts of conflicts in our and possibly other people's projects.

And frankly, I don't think jQuery is absolutely necessary. Tabbing can be accomplished with a couple of lines of JS/CSS. It's hard to justify pulling in such a large dependency while it could be done much simpler.

**Comment by si14** [comment]
I'm sorry for my slow answers, I'll try to do better.

Agreed, we can redo this with simpler client-side code, will do. Is there anything else that should be fixed before we can merge this? I will look through the code once more for typos and code smells, but if you have any big concerns I would really appreciate your input.

**Comment by Photonios** [comment]
Other than that, the `LocalizedModel` class cannot be removed that easily. Even though the new solution (using `descriptor_class`) is very elegant, in the latest HEAD, it is also used to guarantee concurrency safety. It is optional to be used, but I'd advise to do so.

I am also wondering whether the `LocalizedValue` class is maybe irrelevant now, since the `LocalizedValueDescriptor` seems to be just a proxy now.

Could you maybe split the changes into:

* Addition of new fields (`LocalizedTextField` etc)
* Introduction of `LocalizedValueDescriptor`
* Addition of new form fields and admin integration

Please let me know if this would be an acceptable approach. Because honestly, this PR involves so many changes that it's hard to keep track of them all and be sure none of them break anything.

**Comment by si14** [comment]
Thanks for your input! I have a question though:

>it is also used to guarantee concurrency safety

I'm probably missing something, but why do you do those retries in the `LocalizedModel`'s `save`? Is HStore somewhat different to other DB types w.r.t. concurrency? If I understand it correctly, the retry code is very generic and can probably be refactored out to something like `AtomicSlugRetryMixin` (if not handled on a `Model.save` call site), isn't it? This way we can make that retry logic completely optional and specific to slug fields.

**Comment by Photonios** [comment]
You are completely correct. The retry logic should be moved out into a mixin.

Let me explain how this guarentees concurrency safety. I've added support for unique constraints on hstore keys on a database level. Meaning that if you try to insert the same key twice, the database will throw an error.

The old slug implementation would do a SELECT to check whether the generated slug already exists. If it would, it would generate a new one and try again, and so on until it would find a "unique" one. It then would finally do the INSERT. Between the SELECT and INSERT, another process could find the same slug and insert it just before the INSERT. The result would be non-unique slugs. We've seen this happening in our production environments.

The solution is to avoid the SELECT. Now that there's a constraint, the database will raise an error when trying to insert a duplicate. In order to save time and avoid mistakes, we attempt the INSERT for a slug and retry with a different one until it passes.

The retry logic cannot be in the LocalizedMagicSlugField, since it has no control over when the insert happens. You can catch the 'pre_save' in a custom field, but it doesn't allow you to catch the actual insertion to retry it. So the mixin will have to be a model mixin overriding Model.save. Unless you can think of a better approach, then that would be awesome. Because this is less than optimal.

However, you are right, the retry logic is rather generic. There's a small "hack" in there that would prevent catching all exceptions, but it's far from optimal. I'll make a change that will use a mixin. Thanks for the feedback on that one.

**Pull request closed without merging**
