### PR TITLE
Extra fields

### PR DESCRIPTION
**Pull request by seroy**
added new LocalizedCharField, LocalizedTextField and LocalizedFileField fields and widgets

### CODE REVIEW

**Comment by seroy** [comment]
* ``LocalizedBleachField``
     Automatically bleaches the content of the field.
          * django-bleach

     Example usage:

           .. code-block:: python

              from localized_fields import (LocalizedField,
                                            LocalizedBleachField)

              class MyModel(models.Model):
                   title = LocalizedField()
                   description = LocalizedBleachField()

**Comment by seroy** [comment]
`LocalizedCharField` and `LocalizedTextField` following the [Django convention](https://docs.djangoproject.com/en/1.11/ref/models/fields/#null) for string-based fields uses the empty string as value for “no data”, not NULL as LocalizedField. It is best to demonstrate by example:

```
# Suppose we have a model

class MyModel(models.Model):
    localized_field = LocalizedField(null=True)
    char_field = LocalizedCharField(null=True)     # in fact for this field type null=True is not necessary

# Then we create new instance and save this

>>> instance = MyModel()
>>> instance.save()

# In result, we have

>>> instance.char_field
LocalizedStingValue<{'ro': '', 'nl': '', 'en': ''}> 0x140074115948360

>>> instance.localized_field
LocalizedValue<{'ro': None, 'nl': None, 'en': None}> 0x140074115947800

# in template we will get "None" for LocalizedField and empty string for LocalizedCharField

>>> str(instance.char_field.en)
'None'

>>> str(instance.localized_field.en)
''

```
The end result in the database is different: `localized_field = null` and `char_field = 'en => , ro => , nl => ' `(or if value will be present for one lang we will get for `localized_field = 'en => 'test', ro => null, nl => null'`, and `char_field = 'en => test, ro => , nl => '`).

If `LocalizedField` will handle "no data" in django way, then `LocalizedStringValue` and `LocalizedTextField` is not needed, this was added as not violating backward compatibility of `LocalizedField`.

Next, yes, currently ``LocalizedCharField`` and ``LocalizedTextField`` has only one difference is the associated form field. And yes, that can be handled in a different way (define widget in form class for example), but as a end-user of ``django-localized-fields`` can say that it would be very nice to have field with ``<input>`` widget out of box and do not redefine widget for each field in each form or/and not copy paste custom field implementation from project to project.

I can add `max_length` parametter and validator as in django `CharField`, for more functionality.

Finally, I absolutely agree about the tests and will add these.

**Comment by si14** [comment]
Hey @Photonios, what do you think about the PR in its current form? :)

Generally speaking it seems that we use the library in a lot of unexpected ways :) However, I strongly believe that the code we've added is generally useful and makes `django-localized-fields` an awesome drop-in solution for model localization that covers most use cases. We were able to migrate all our models to it with minimal effort with those changes, so I believe it's only fair to contribute them back!

**Comment by Photonios** [comment]
Sorry @si14, as I mentioned in the comment to the issue I created, I have been slacking replying to stuff. My apologies. I really appreciate the work you guys have been doing on this library. It's great to see it's useful to others and I really appreciate you guys contributing the changes back upstream, despite my rather depressing stewardship.

I looked over this PR and I think it's good to merge, assuming you fix the type `LocalizedStingValue` should be `LocalizedString`, you're missing an `r` there ;)

**Comment by seroy** [comment]
Hey @Photonios!
Sorry for slow feedback. Now is all ready for merge.

**Pull request merged**
